#!/bin/bash

ARG1=$1
ARG2=$2
VERSION="0.1"
BUILD="0.1.5"

if [[ $EUID -ne 0 ]]; then
    echo "OpenCall requires root privileges"
    exit 1
fi

if [ "$ARG1" == "install" ] && [ "$ARG2" == "server" ]; then
source /etc/os-release

    ############# BEGIN - OpenCall Server - DEBIAN INSTALLATION ###############
    if [ "$ID" == "debian" ] && [ "$VERSION_ID" == "9" -o "$VERSION_ID" == "10" ]; then

        echo -e "\nOpenCall Server - Debian $VERSION_ID - Installation\n"
        sleep 1

        apt -y install asterisk asterisk-opus openssl
        mkdir -p /etc/opencall
        cp ./opencall /bin/opencall

        ######### BEGIN - SELF SIGNED CERTIFICATE CREATION ########
        mkdir -p /etc/asterisk/keys

        echo -e "\n\n\n<-- Self Signed SSL Certificate Creation -->\n"
        echo -en "Insert Server IP Address or Domain Name\n[e.g. 192.168.1.100 or example.com]: "
        read SERVER_ADDRESS

        openssl req -x509 -newkey rsa:4096 -keyout /etc/asterisk/keys/key.pem \
                -out /etc/asterisk/keys/cert.pem -days 365 \
                -nodes -subj '/CN=$SERVER_ADDRESS'
        cat /etc/asterisk/keys/key.pem > /etc/asterisk/keys/asterisk.pem
        cat /etc/asterisk/keys/cert.pem >> /etc/asterisk/keys/asterisk.pem
        rm /etc/asterisk/keys/key.pem
        rm /etc/asterisk/keys/cert.pem

        echo "SERVER_ADDRESS=$SERVER_ADDRESS" > /etc/opencall/opencall.conf

        echo -e "\n\nSELF SIGNED CERTIFICATE CREATED: $SERVER_ADDRESS\n\n"
        sleep 1
        ######### END - SELF SIGNED CERTIFICATE CREATION ########


        ######### BEGIN - /ETC/ASTERISK/HTTP.CONF CONFIGURATION ########

        #enabled=yes
        sed -i '/;enabled=/ c enabled=yes' /etc/asterisk/http.conf
        sed -i '/^enabled=/ c enabled=yes' /etc/asterisk/http.conf

        #bindaddr=0.0.0.0
        sed -i '/;bindaddr=/ c bindaddr=0.0.0.0' /etc/asterisk/http.conf
        sed -i '/^bindaddr=/ c bindaddr=0.0.0.0' /etc/asterisk/http.conf

        #bindport=8088
        sed -i '/;bindport=/ c bindport=8088' /etc/asterisk/http.conf
        sed -i '/^bindport=/ c bindport=8088' /etc/asterisk/http.conf

        #tlsenable=yes
        sed -i '/;tlsenable=/ c tlsenable=yes' /etc/asterisk/http.conf
        sed -i '/^tlsenable=/ c tlsenable=yes' /etc/asterisk/http.conf

        #tlsbindaddr=0.0.0.0:8089
        sed -i '/;tlsbindaddr=/ c tlsbindaddr=0.0.0.0:8089' /etc/asterisk/http.conf
        sed -i '/^tlsbindaddr=/ c tlsbindaddr=0.0.0.0:8089' /etc/asterisk/http.conf

        #tlscertfile=/etc/asterisk/keys/asterisk.pem
        sed -i '/;tlscertfile=/ c tlscertfile=/etc/asterisk/keys/asterisk.pem' /etc/asterisk/http.conf
        sed -i '/^tlscertfile=/ c tlscertfile=/etc/asterisk/keys/asterisk.pem' /etc/asterisk/http.conf

        #tlsprivatekey=/etc/asterisk/keys/asterisk.pem
        sed -i '/;tlsprivatekey=/ c tlsprivatekey=/etc/asterisk/keys/asterisk.pem' /etc/asterisk/http.conf
        sed -i '/^tlsprivatekey=/ c tlsprivatekey=/etc/asterisk/keys/asterisk.pem' /etc/asterisk/http.conf

        ######### END - /ETC/ASTERISK/HTTP.CONF CONFIGURATION ########


        ######### BEGIN - /ETC/ASTERISK/PJSIP.CONF CONFIGURATION ########

        ######### END - /ETC/ASTERISK/PJSIP.CONF CONFIGURATION ########


        ######### BEGIN - /ETC/ASTERISK/SIP.CONF CONFIGURATION ########

        ######### END - /ETC/ASTERISK/SIP.CONF CONFIGURATION ########


        ######### BEGIN - /ETC/ASTERISK/MODULES.CONF CONFIGURATION ########
        #disable chan_sip.so
        ######### END - /ETC/ASTERISK/MODULES.CONF CONFIGURATION ########

    ############# END - OpenCall Server - DEBIAN INSTALLATION ###############

    else
        echo -e "\nOS NOT SUPPORTED\n"
    fi
fi
